export {default as Header} from './header/Header';
export {default as Footer} from './footer/Footer';
export {default as Module_Intro} from './module_Intro/Module_Intro';
export {default as Module_Techniques} from './module_Techniques/Module_Techniques';
export {default as Module_Applications} from './module_Applications/Module_Applications';
export {default as Module_Challenges} from './module_Challenges/Module_Challenges';
export {default as Module_Conclusions} from './module_Conclusions/Module_Conclusions';
export {default as Module_Login} from './module_Login/Module_Login';
export {default as Module_Dashboard} from './module_Dashboard/Module_Dashboard';